/**:
  ros__parameters:
  # Ioniq5 in MORAI
    wheel_radius: 0.36 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.255 #todo # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 3.0 # between front wheel center and rear wheel center
    wheel_tread: 1.64 #todo # between left wheel center and right wheel center
    front_overhang: 0.845 # between front wheel center and vehicle front
    rear_overhang: 0.79 # between rear wheel center and vehicle rear
    left_overhang: 0.128 #todo # between left wheel center and vehicle left
    right_overhang: 0.128 #todo # between right wheel center and vehicle right
    vehicle_height: 1.892
    max_steer_angle: 0.69 # [rad]
